export {
  addDomain,
  deleteDomain,
  dnsRecords,
  domainById,
  listDomains,
  recipientsForDomain,
  updateDomainSettings,
  verificationStatus,
} from "./domains.module";

export {
  type AddDomainData,
  type AddDomainParams,
  type AddDomainResponse,
  type DeleteDomainResponse,
  type DnsRecordsData,
  type DnsRecordsResponse,
  type DomainByIdData,
  type DomainByIdResponse,
  type ListDomainsData,
  type ListDomainsParams,
  type ListDomainsResponse,
  type RecipientsForDomainData,
  type RecipientsForDomainParams,
  type RecipientsForDomainResponse,
  type UpdateDomainSettingsData,
  type UpdateDomainSettingsParams,
  type UpdateDomainSettingsResponse,
  type VerificationStatusData,
  type VerificationStatusResponse,
} from "./domains.types";
