name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MAILERSEND_API_KEY: ${{ secrets.MAILERSEND_API_KEY }}
  MAILERSEND_DOMAIN_ID: ${{ secrets.MAILERSEND_DOMAIN_ID }}
  MAILERSEND_MESSAGE_ID: ${{ secrets.MAILERSEND_MESSAGE_ID }}
  MAILERSEND_TEMPLATE_ID: ${{ secrets.MAILERSEND_TEMPLATE_ID }}
  MAILERSEND_TEST_DOMAIN: ${{ secrets.MAILERSEND_TEST_DOMAIN }}
  MAILERSEND_TEST_RECIPIENT_EMAIL: ${{ secrets.MAILERSEND_TEST_RECIPIENT_EMAIL }}
  MAILERSEND_TEST_SENDER_EMAIL: ${{ secrets.MAILERSEND_TEST_SENDER_EMAIL }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build:prod

      - name: Test
        run: yarn test
